
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Starter pipeline
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Test Run'
    organization: 'seckkosonarcloud'
    scannerMode: 'MSBuild'
    projectKey: 'sonar-test-run'
    projectName: 'Sonar Test Run'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'